#!/bin/bash
# Hi sir, I am parneet kaur.
# I don't properly know how to use variables, but i will use echo to get results.
# first of all i need to type system report generated and all.
echo " System Report generated by $(whoami), $(date)"
# Now i need to give system information.
echo "---------------------"
echo "System Information"
echo "---------------------"
echo "Hostname: $(hostname)"
echo "OS: $(source /etc/os-release && echo $PRETTY_NAME)"
echo "Uptime: $(uptime -p)"
echo "---------------------"
# after the basic commands now the next part requires filters.
# because the basic commands give too much of the information.
# Hardware Information
echo "Hardware Information"
echo "---------------------"
echo "CPU: $(lscpu | grep 'Model name' | awk -F': ' '{print $2}')"
echo "Speed: $(sudo lshw -class processor | awk '/description: CPU/{p=1} p && /size:/{print $2; exit}')"
echo "MAX Speed: $(sudo lshw -class processor | awk '/description: CPU/{p=1} p && /capacity:/{print $2; exit}')"
echo "RAM: $(sudo lshw -short -C memory | grep -i 'system memory' | awk '{print $3}')"
echo "Disks: $(lsblk --output NAME,SIZE,TYPE,MOUNTPOINT,LABEL --exclude 7 | awk '!/loop/ {printf "%-8s %-8s %-4s %-8s %-7s %s\n", $1, $2, $3, $4, $5, $6}')"
echo "Video card: $(lspci -nnk | grep -i 'VGA' | awk -F': ' '{print $2}' | uniq)"

echo "---------------------"
# now we will try to extract the network information.
# ip commands and lshw are enough.
# Network Information
echo "Network Information"
echo "---------------------"
echo "FQDN: $(hostname -f)"
echo "Host Address: $(ip a show dev $(ip r | awk '/default/ {print $5}') | awk '/inet / {print $2}')"
echo "Gateway IP: $(ip r | awk '/default/ {print $3}')"
echo "DNS Server: $(grep -E '^nameserver' /etc/resolv.conf | awk '{print $2}')"
echo "Network Interface Information:"
echo "$(sudo lshw -class network | grep -E 'description|product|vendor|physical id|logical name' | awk -F ':' '{print $1 ": " $2}')"

echo "IP Address: $(ip a show dev $(ip r | awk '/default/ {print $5}') | awk '/inet / {print $2}')"
echo "---------------------"
# then finally we will get system status commands.
# System Status
echo "System Status"
echo "---------------------"
echo "Users Logged In: $(who | awk '{print $1}' | sort | uniq | paste -s -d ',')"
echo "Disk Space: $(df -h)"
echo "Process Count: $(ps -e | wc -l)"
echo "Load Averages: $(uptime | awk -F'[a-z]:' '{print $2}')"
echo -e "Memory Allocation:\n$(free -h | awk '/^Mem:/ {print "Type\tTotal\tAvailable"; print $1 "\t" $2 "\t" $7}')"

echo -e "Listening Network Ports:\n$(ss -tuln)"

echo "UFW Rules: $(sudo ufw status numbered | grep -v 'Status: active')"
